services:
  pictaccio-routing-controllers-openapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:z
    ports:
      - "8000:8000"
    environment:
      - ENV=development